-- MySQL Script generated by MySQL Workbench
-- Sun Apr  9 19:24:48 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ksjdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ksjdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ksjdb` DEFAULT CHARACTER SET utf8 ;
USE `ksjdb` ;

-- -----------------------------------------------------
-- Table `ksjdb`.`corp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ksjdb`.`corp` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '企业',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `state` TINYINT(4) ZEROFILL NULL DEFAULT 0,
  `name` VARCHAR(100) NULL,
  `address` VARCHAR(100) NULL,
  `shortname` VARCHAR(45) NULL,
  `createrid` INT NULL COMMENT '创建者id',
  `creater` VARCHAR(45) NULL COMMENT '创建者姓名',
  `createrrole` TINYINT(4) NULL DEFAULT 0 COMMENT '管理员，运营人员，用户',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `identerprise_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ksjdb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ksjdb`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `state` TINYINT(4) ZEROFILL NULL DEFAULT 0,
  `phone` VARCHAR(20) NULL,
  `password` VARCHAR(100) NULL,
  `nickname` VARCHAR(45) NULL,
  `iconurl` VARCHAR(200) NULL,
  `username` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `score` INT NULL DEFAULT 0 COMMENT '积分',
  `corpid` INT NULL,
  `corpname` VARCHAR(45) NULL COMMENT '公司简称',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `iduser_UNIQUE` (`id` ASC),
  CONSTRAINT `usercorpid`
    FOREIGN KEY (`id`)
    REFERENCES `ksjdb`.`corp` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '用户表';


-- -----------------------------------------------------
-- Table `ksjdb`.`pushmsg`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ksjdb`.`pushmsg` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `state` TINYINT(4) ZEROFILL NULL DEFAULT 0,
  `content` VARCHAR(200) NULL,
  `userid` INT NULL,
  `corpid` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `iduserinfo_UNIQUE` (`id` ASC),
  CONSTRAINT `pushmsguserid`
    FOREIGN KEY (`id`)
    REFERENCES `ksjdb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `pushmsgcorpid`
    FOREIGN KEY (`id`)
    REFERENCES `ksjdb`.`corp` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ksjdb`.`invoiceinfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ksjdb`.`invoiceinfo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `state` TINYINT(4) ZEROFILL NULL DEFAULT 0,
  `title` VARCHAR(100) NULL,
  `type` TINYINT(4) NULL COMMENT '发票种类：企业，个人',
  `userid` VARCHAR(45) NULL,
  `corpid` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idinvoiceinfo_UNIQUE` (`id` ASC),
  CONSTRAINT `invoiceinfouserid`
    FOREIGN KEY (`id`)
    REFERENCES `ksjdb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `invoiceinfocorpid`
    FOREIGN KEY (`id`)
    REFERENCES `ksjdb`.`corp` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ksjdb`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ksjdb`.`address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `state` TINYINT(4) ZEROFILL NULL DEFAULT 0,
  `userid` INT NULL,
  `detail` VARCHAR(100) NULL,
  `contactname` VARCHAR(45) NULL,
  `contactphone` VARCHAR(20) NULL,
  `province` VARCHAR(20) NULL,
  `city` VARCHAR(20) NULL,
  `district` VARCHAR(20) NULL,
  `street` VARCHAR(20) NULL,
  `corpid` INT NULL,
  `priority` TINYINT(4) NULL COMMENT '用户默认收货地址为优先级最高的地址',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `addressuserid`
    FOREIGN KEY (`id`)
    REFERENCES `ksjdb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `addresscorpid`
    FOREIGN KEY (`id`)
    REFERENCES `ksjdb`.`corp` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ksjdb`.`instrument`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ksjdb`.`instrument` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `state` TINYINT(4) ZEROFILL NULL DEFAULT 0,
  `userid` INT NOT NULL,
  `validdate` DATE NULL COMMENT '有效日期',
  `name` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `serialno` VARCHAR(45) NULL COMMENT '出厂编号',
  `dept` VARCHAR(45) NULL COMMENT '实用部门',
  `manufacturer` VARCHAR(100) NULL COMMENT '生产厂家',
  `lab` VARCHAR(45) NULL,
  `price` INT NULL COMMENT '预估报价',
  `measrange` VARCHAR(45) NULL COMMENT '测量范围',
  `certno` VARCHAR(45) NULL COMMENT '证书编号',
  `uniformno` VARCHAR(45) NULL COMMENT '统一编号',
  `incart` TINYINT(1) NULL DEFAULT 0 COMMENT '在送检车中',
  `corpid` INT NOT NULL,
  `rank` VARCHAR(45) NULL COMMENT '准确度等级',
  `manager` VARCHAR(45) NULL COMMENT '负责人',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idinstrument_UNIQUE` (`id` ASC),
  CONSTRAINT `instrument_userid`
    FOREIGN KEY (`id`)
    REFERENCES `ksjdb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `instrument_corpid`
    FOREIGN KEY (`id`)
    REFERENCES `ksjdb`.`corp` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '器具表';


-- -----------------------------------------------------
-- Table `ksjdb`.`lab`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ksjdb`.`lab` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `state` TINYINT(4) ZEROFILL NULL DEFAULT 0,
  `name` VARCHAR(100) NULL,
  `address` VARCHAR(100) NULL,
  `shortname` VARCHAR(45) NULL,
  `createrid` INT NULL COMMENT '创建者id',
  `creater` VARCHAR(45) NULL COMMENT '创建者姓名',
  `createrrole` TINYINT(4) NULL DEFAULT 0 COMMENT '管理员，运营人员',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idlab_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ksjdb`.`aorder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ksjdb`.`aorder` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '委托单',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `state` TINYINT(4) ZEROFILL NULL DEFAULT 0,
  `no` VARCHAR(45) NULL,
  `feetotal` INT NULL,
  `feefreight` INT NULL COMMENT '运费',
  `feerepair` INT NULL,
  `instrumentids` VARCHAR(100) NULL,
  `userid` INT NULL,
  `instrumentnames` VARCHAR(200) NULL,
  `corpid` INT NULL,
  `from` TINYINT(4) NULL COMMENT '来源\n1. ios\n2.android\n3. pc',
  `detectway` TINYINT(2) NULL COMMENT '0:实验室检测\n1:现场检查',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `aorderuserid`
    FOREIGN KEY (`id`)
    REFERENCES `ksjdb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `aordercorpid`
    FOREIGN KEY (`id`)
    REFERENCES `ksjdb`.`corp` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '委托单';


-- -----------------------------------------------------
-- Table `ksjdb`.`border`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ksjdb`.`border` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '送检单',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `state` TINYINT(4) ZEROFILL NULL DEFAULT 0,
  `no` VARCHAR(45) NULL,
  `feetotal` INT NULL,
  `feefreight` INT NULL COMMENT '运费',
  `feerepair` INT NULL,
  `instrumentids` VARCHAR(100) NULL,
  `userid` INT NULL,
  `instrumentnames` VARCHAR(200) NULL,
  `aorderid` INT NULL,
  `corpid` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `borderuserid`
    FOREIGN KEY (`id`)
    REFERENCES `ksjdb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `borderaorderid`
    FOREIGN KEY (`id`)
    REFERENCES `ksjdb`.`aorder` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `bordercorpid`
    FOREIGN KEY (`id`)
    REFERENCES `ksjdb`.`corp` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '送检单';


-- -----------------------------------------------------
-- Table `ksjdb`.`certlog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ksjdb`.`certlog` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `state` TINYINT(4) ZEROFILL NULL DEFAULT 0,
  `instrumentid` INT NULL,
  `aorderid` INT NULL,
  `borderid` INT NULL,
  `feetotal` INT NULL COMMENT '总检测费用，下一次送检的报价参考',
  `feefreight` INT NULL COMMENT '运费',
  `feerepair` INT NULL,
  `userid` INT NULL,
  `corpid` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `certlog_instrumentid`
    FOREIGN KEY (`id`)
    REFERENCES `ksjdb`.`instrument` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `certlog_aorderid`
    FOREIGN KEY (`id`)
    REFERENCES `ksjdb`.`aorder` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `certlog_borderid`
    FOREIGN KEY (`id`)
    REFERENCES `ksjdb`.`border` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `certlog_userid`
    FOREIGN KEY (`id`)
    REFERENCES `ksjdb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `certlog_corpid`
    FOREIGN KEY (`id`)
    REFERENCES `ksjdb`.`corp` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '器具的送检记录，送检历史，维修记录';


-- -----------------------------------------------------
-- Table `ksjdb`.`distribution`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ksjdb`.`distribution` (
  `id` INT NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `state` TINYINT(4) ZEROFILL NULL DEFAULT 0,
  `no` VARCHAR(45) NULL COMMENT '送检单号',
  `borderid` INT NULL,
  `deliverer` VARCHAR(45) NULL COMMENT '物流人员，配送员',
  PRIMARY KEY (`id`),
  CONSTRAINT `distrib_borderid`
    FOREIGN KEY (`id`)
    REFERENCES `ksjdb`.`border` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '物流单、指派单';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
